---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: configserver
  labels:
    app: configservr
  namespace: sapo-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configserver
  template:
    metadata:
      labels:
        app: configserver
    spec:
      containers:
      - name: configserver
        image: hub.bizweb.vn/fnb-configserver
        ports:
        - containerPort: 80
          protocol: TCP
      imagePullSecrets:
        - name: regcred
